// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    smart_account_deployer
    (
        init => init
        upgrade => upgrade
        deploySmartAccount => deploy_smart_account
        upgradeSmartAccount => upgrade_smart_account
        initializeSmartAccount => initialize_smart_account
        setFarmStakingAddressForToken => set_farm_staking_address_for_token
        setAdminAddress => set_admin_address
        getUserSmartAccount => user_smart_account
        getAdminAddress => admin_address
        getSmartAccountOpenFee => smart_account_open_fee
        getSmartAccountTemplateAddress => smart_account_template_address
        getFarmStakingAddressForToken => farm_staking_address_for_token
        getEgldWrapperAddress => egld_wrapper_address
        setStrategiesPerEpoch => set_strategies_per_epoch
        getStrategies => strategies
        getLastStrategyEpoch => last_strategy_epoch
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
