// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    smart_account
    (
        init => init
        upgrade => upgrade
        setupSmartAccount => setup_smart_account
        getUserStrategy => user_strategy
        getUserPortfolio => user_portfolio
        getUserRiskTolerance => user_risk_tolerance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
